name: specular_cvae
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - numpy
  - opencv
  - pillow
  - matplotlib
  - tqdm
  - scikit-image
  - einops
  - pip
  - pip:
      - lpips
